// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"navbar fixed-top navbar-expand-lg bg-body-tertiary bg-dark\" data-bs-theme=\"dark\"><div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"/\">WebApp</a> <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button><div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\"><ul class=\"navbar-nav mb-2 mb-lg-0\"><li class=\"nav-item\"><a class=\"nav-link\" href=\"/customer/\">Customers</a></li><li class=\"nav-item\"><a class=\"nav-link\" href=\"/customer/v2\">CustomersV2</a></li><li class=\"nav-item dropdown\"><a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Reports</a><ul class=\"dropdown-menu\"><li><a class=\"dropdown-item\" href=\"/reports/1\">One</a></li><li><a class=\"dropdown-item\" href=\"/reports/2\">Two</a></li></ul></li></ul><div style=\"width: 50px\"></div><div class=\"d-flex flex-nowrap\"><form action=\"/search/v2\" method=\"get\" class=\"form-inline\"><div class=\"d-flex\"><input id=\"filter\" name=\"filter\" class=\"form-control form-control-sm\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" hx-get=\"/search/v2\" hx-target=\"#searchResult\" hx-swap=\"outerHTML\" hx-trigger=\"search, keyup delay:200ms changed\" onkeydown=\"return event.keyCode !== 13\"></div></form>&nbsp; <button class=\"btn btn-sm btn-success\" hx-get=\"/search/v2\" hx-target=\"#searchResult\" hx-swap=\"outerHTML\" onclick=\"resetSearch()\">Clear</button></div></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
